web:
    image: nginx
    ports:
        - "8080:80"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./static:/www/static:ro
    links:
        - django
    restart: always

django:
    build: .
    expose:
        - "5000"
    volumes:
        - .:/opt/app
    links:
        - mysql
    restart: always

mysql:
    image: zhongpei/mysql
    ports:
        - "127.0.0.1:3306:3306"
    expose:
        - "3306"
    volumes:
        - ./data/mysql:/var/lib/mysql
    environment:
        - "MYSQL_ROOT_PASSWORD=12345678"
        - "MYSQL_DATABASE=ssdjango"
    restart: always
